# Generated by Django 4.0.5 on 2022-06-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_doctor', '0002_alter_doctor_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['name', 'id'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='lineofaction',
            options={'ordering': ['title'], 'verbose_name': 'LineOfAction', 'verbose_name_plural': 'LineOfAction'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='line_of_action',
            field=models.ManyToManyField(help_text='Select a line of action for this doctor', related_name='doctor_info', to='info_doctor.lineofaction'),
        ),
    ]
